POST https://babylon-mvp-backend.onrender.com/usuario
Content-Type: application/json


{
  "genero": "m",
  "gmail": "matheus@gmail.com",
  "idade": "21",
  "nome": "masgdsgMatheus",
  "senha": "matheus123",
  "telefone": "1920897346796"
}

